#ifndef WATCHY_APP_DEFAULTS_H
#define WATCHY_APP_DEFAULTS_H

#ifndef HEALTHCARE_UN_DOG_PLATE_NAME
#define HEALTHCARE_UN_DOG_PLATE_NAME "NOT SET"
#endif

#ifndef HEALTHCARE_UN_DOG_PLATE_IDENTIFIER
#define HEALTHCARE_UN_DOG_PLATE_IDENTIFIER "NOT SET"
#endif

#ifndef HEALTHCARE_UN_DOG_PLATE_COUNTRY
#define HEALTHCARE_UN_DOG_PLATE_COUNTRY "NOT SET"
#endif

#ifndef HEALTHCARE_UN_DOG_PLATE_BIRTH_DATE
#define HEALTHCARE_UN_DOG_PLATE_BIRTH_DATE "NOT SET"
#endif

#ifndef HEALTHCARE_UN_DOG_PLATE_BLOOD_TYPE
#define HEALTHCARE_UN_DOG_PLATE_BLOOD_TYPE "NOT SET"
#endif

#ifndef HEALTHCARE_MEDICAL_ID_ALLERGIES
#define HEALTHCARE_MEDICAL_ID_ALLERGIES "NOT SET"
#endif

#ifndef HEALTHCARE_MEDICAL_ID_CONDITIONS
#define HEALTHCARE_MEDICAL_ID_CONDITIONS "NOT SET"
#endif

#ifndef HEALTHCARE_MEDICAL_ID_MEDICATIONS
#define HEALTHCARE_MEDICAL_ID_MEDICATIONS "NOT SET"
#endif

#ifndef HEALTHCARE_ICE_CONTACT_NAME
#define HEALTHCARE_ICE_CONTACT_NAME "NOT SET"
#endif

#ifndef HEALTHCARE_ICE_CONTACT_PHONE
#define HEALTHCARE_ICE_CONTACT_PHONE "NOT SET"
#endif

#ifndef HEALTHCARE_SYMPTOM_NOTE_TEXT
#define HEALTHCARE_SYMPTOM_NOTE_TEXT "NOT SET"
#endif

#ifndef FALL_MONITORING_DEFAULT_ENABLED
#define FALL_MONITORING_DEFAULT_ENABLED 0
#endif

#ifndef FALL_MONITORING_ANY_MOTION_THRESHOLD
#define FALL_MONITORING_ANY_MOTION_THRESHOLD 1843
#endif

#ifndef FALL_MONITORING_ANY_MOTION_DURATION
#define FALL_MONITORING_ANY_MOTION_DURATION 2
#endif

#ifndef NETWORKING_BROWSER_URL
#define NETWORKING_BROWSER_URL "https://example.com"
#endif

#ifndef NETWORKING_RSS_FEED_CUSTOM_URL
#define NETWORKING_RSS_FEED_CUSTOM_URL "https://"
#endif

#ifndef NETWORKING_PING_HOST
#define NETWORKING_PING_HOST "1.1.1.1"
#endif

#ifndef NETWORKING_TRACEROUTE_HOST
#define NETWORKING_TRACEROUTE_HOST "1.1.1.1"
#endif

#ifndef NETWORKING_PORT_SCANNER_HOST
#define NETWORKING_PORT_SCANNER_HOST "AUTO"
#endif

#ifndef NETWORKING_PORT_SCANNER_FALLBACK_HOST
#define NETWORKING_PORT_SCANNER_FALLBACK_HOST "192.168.1.1"
#endif

#ifndef NETWORKING_DNS_QUERY_NAME
#define NETWORKING_DNS_QUERY_NAME "example.com"
#endif

#ifndef NETWORKING_REVERSE_DNS_ADDRESS
#define NETWORKING_REVERSE_DNS_ADDRESS "1.1.1.1"
#endif

#ifndef NETWORKING_DUCKDUCKGO_QUERY
#define NETWORKING_DUCKDUCKGO_QUERY "esp32"
#endif

#endif